services:
  python-mongodb-rest-api:
    build: .
    image: python-mongodb-rest-api
    ports:
      - "5000:80"
    env_file:
      - .env
    volumes:
      - .:/src
    environment:
      - DD_SERVICE=python-mongodb-rest-api
      - DD_ENV=production
      - DD_VERSION=1.0.0
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED="true"
      - DD_TRACE_AGENT_URL=http://datadog-agent:8126
    depends_on:
      - datadog-agent

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    environment:
      - DD_API_KEY=2e665b56cdb13ec923eaa091c6b9cd6c
      - DD_SITE=us5.datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro