# Use the official ASP.NET Core runtime as the base image
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80

# Use the official .NET SDK as the build image
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["MongoDB.REST.csproj", "./"]
RUN dotnet restore "./MongoDB.REST.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "MongoDB.REST.csproj" -c Release -o /app/build
RUN dotnet publish "MongoDB.REST.csproj" -c Release -o /app/publish 

# Final stage/image
FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "MongoDB.REST.dll"]
