services:
  php-laravel-mongodb-rest-api:
    build: .
    image: php-lavavel-mongodb-rest-api
    ports:
      - '8080:80'
    env_file:
      - .env
    volumes:
      - ./.env:/var/www/html/.env
      - ./src:/var/www/html