services:
  php-laravel-mongodb-rest-api:
    build: .
    image: php-lavavel-mongodb-rest-api
    ports:
      - '8080:80'
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/local-php.ini